spring:
  profiles.active: default
---
spring:
  profiles: default
  datasource:
    driverClassName: org.postgresql.Driver
    url:
    username:
    password:

---
spring:
  profiles: dev
---
spring:
  profiles: prod

