spring:
  profiles.active: default
---
spring:
  profiles: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/emptyapp_development
    username: hegel_admin
    password: hegelrockSSs

---
spring:
  profiles: dev
  datasource:
    url:
    username:
    password:
---
spring:
  profiles: prod
  datasource:
    url:
    username:
    password:
